name: shelf_rest
version: 1.0.0

description: Web Server Middleware for Dart
author: Dart Team <misc@dartlang.org>
homepage: https://github.com/dart-lang/shelf

environment:
  sdk: '>=2.0.0-dev.61.0 <3.0.0'

dependencies:
  shelf: ^0.7.3
  intl: ^0.15.7
